import{a as S,S as q,i as n}from"./assets/vendor-DQvd0HNi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const M="55203638-ed2d579cf4ced86cd2d49b188",P="https://pixabay.com/api/";async function p(s,t=1){const a={key:M,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await S.get(P,{params:a})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new q(".gallery a",{captionsData:"alt",captionDelay:250});function h(s){const t=s.map(({webformatURL:a,largeImageURL:o,tags:e,likes:r,views:c,comments:v,downloads:w})=>`
<li class="gallery-item">
  <a href="${o}">
    <img src="${a}" alt="${e}" />
  </a>
  <div class="info">
  <p><span class="label">Likes</span><span>${r}</span></p>
  <p><span class="label">Views</span><span>${c}</span></p>
  <p><span class="label">Comments</span><span>${v}</span></p>
  <p><span class="label">Downloads</span><span>${w}</span></p>
</div>
</li>`).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function $(){f.innerHTML=""}function g(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function b(){y.classList.add("visible")}function d(){y.classList.remove("visible")}const E=document.querySelector(".form"),O=document.querySelector(".load-more");let l="",i=1,u=0;E.addEventListener("submit",async s=>{if(s.preventDefault(),l=s.target.elements["search-text"].value.trim(),!l){n.error({message:"Please enter a search query!"});return}i=1,$(),g();try{d();const t=await p(l,i);if(u=t.totalHits,t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(t.hits);const a=Math.ceil(u/15);i<a?b():(d(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch{n.error({message:"Something went wrong. Try again!"})}finally{L()}});O.addEventListener("click",async()=>{i+=1;try{g(),d();const s=await p(l,i);h(s.hits);const t=Math.ceil(u/15);i>=t?(d(),n.info({message:"We're sorry, but you've reached the end of search results."})):b();const o=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:o.height*2,behavior:"smooth"})}catch{n.error({message:"Error loading more images"})}finally{L()}});
//# sourceMappingURL=index.js.map
